### ISSUE TITLE
Criar variável de ambiente informando se o ambiente é de teste e modo de debug

### ISSUE THREAD

**Issue by wesleywillians** [codeedu/codeedu-plataforma-desafios#1]
No arquivo .env, devemos informar se o ambiente em que a aplicação está sendo executada é o ambiente de teste ou de produção.

Também deverá ser criada uma variável informando se o modo debug deve ser "true" ou "false". Caso seja "true", logs como de banco de dados devem ser exibidos durante a execução do software.

**Comment by duanyrf** [comment]
@wesleywillians sugiro fechar esta issue, pois observei que os requisitos dela já foram atendidos.
Abraços.
